## SAM template for CodeBuild
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple AWS Lambda for searching game records within a DynamoDB table.
Resources:
  GetGamesFx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/get-games-fx-1.0-SNAPSHOT.jar
      Handler: com.revature.get_games.GetGamesHandler
      Runtime: java8.al2
      Description: Java function
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
      - arn:aws:iam::335686588370:policy/get-games-fx-policy